export const _state = {
  loading: false,
  itemList: [],
  activeTeachers: [],

  selectedIds: [],
  selectedItem: null,
  message: "",
  isSuccessful: false,
  activeSubjects: [],
  activeClasses: [],
  classSubjects: [],
  classStudents: null,
  studentSubjectList:[],

  classRegister:[],
  singleClassRegister:[],
  newClassRegister:[],
  registerLabelUpdateSuccessful:false,
  studentsPresence:null,
  createSuccessful:false,
  sendApprovalSuccessful:false,

  lessonNotes: [],
  unapprovedLessonNotes:[],
  singleLessonNotes:null,
  singleStudentNotes: null,
  studentNotesByTeacher: [],
  studentNotes:[],
  subjectTeacher:[],
  classNotes:[],
  otherStaffList:[],
  comments:[],
  studentComments:[],
  viewers:[],
  relatedNotes:[],
  groupList: [],
  singleGroupList:null,
  assessmentList:[],
  singleHomeAssessment:null,
  singleClassAssessment:null,
  newClassAssessment:null,
  studentSingleHomeAssessment:null,
  assessmentScore:{},
  studentClassAssessment:null,
  scoreRecordList:[],
};