export const _state = {
  loading: false,
  itemList: [],
  activeTeachers: [],

  selectedIds: [],
  selectedItem: null,
  message: "",
  isSuccessful: false,
  activeSubjects: [],
  activeClasses: [],
  classSubjects: [],
  classStudents: null,
  studentSubjectList:[],

  classRegister:[],
  singleClassRegister:[],
  newClassRegister:[],
  registerLabelUpdateSuccessful:false,
  studentsPresence:null,
  createSuccessful:false,

  lessonNotes: [],
  unapprovedLessonNotes:[],
  singleLessonNotes:null,
  singleStudentNotes: null,
  studentNotesByTeacher: [],
  studentNotes:[],
  subjectTeacher:[],
  classNotes:[],
  otherStaffList:[],
  comments:[],
  studentComments:[],
  viewers:[],
  relatedNotes:[],
  groupList: [],
  singleGroupList:null,
  assessmentList:[],
  singleHomeAssessmentList:null,
  singleClassAssessmentList:null,
  newClassAssessment:null,
  studentSingleHomeAssessmentList:null,
  assessmentScore:null,
  studentClassAssessment:null,
};