export const _state = {
  loading: false,
  itemList: [],
  activeTeachers: [],

  selectedIds: [],
  selectedItem: null,
  message: "",
  isSuccessful: false,
  activeSubjects: [],
  activeClasses: [],
  classSubjects: [],
  classStudents: null,

  classRegister:[],
  singleClassRegister:[],
  newClassRegister:[],
  registerLabelUpdateSuccessful:false,
  studentsPresence:null,
  createSuccessful:false,

  lessonNotes: [],
  unapprovedLessonNotes:[],
  singleLessonNotes:null,
  otherStaffList:[],
  comments:[],
  viewers:[],
  relatedNotes:[],
  groupList: [],
  singleGroupList:null,
  assessmentList:[],
  singleHomeAssessmentList:null,
  studentSingleHomeAssessmentList:null,
  assessmentScore:null,
  studentClassAssessment:null,
};