export const _state = {
    loading: false,
    myWardList: [],
    selectedWard: null,
    message: "",
    isSuccessful: false,
    selectedIds: [],
    submitSuccessful: false,
    filterProps: {},
    myWardsClassNotes: [],
    myWardsNotes: [],
    selectedWardsNote: {},
    selectedWardsClassNote: {},
    myWardsHomeAssessment: [],
    myWardsClassTimetable: {},
    selectedWardDetails: {},
    myWardsAnnouncementList: [],
    myWardsSingleAnnouncement: {},
    myWardsExamTimetable:{},
    parents:[],
    singleParent:{},
  };