export const _state = {
    showStickyInfoToast: false,
    showAlertInfoToast: false,
    showStickyErrorToast: false,
    showStickyAlertToast: false,
    showSuccessToast: false,
    showErrorToast: false,
    message: '',
    showSingleDeleteDialog: false,
    showMultipleDeleteDialog: false,
    deleteDialogResponse: '',
    dialogShow: false,
    dialogResponse: '',
    dialogMessage:'',
    showModal: false,
    showTimeOutModal:false,
    modalResponse : '',
    timeOutModalResponse:'',
}