export const NavPermissions = {
    addSessionSetup: 'add-session-setup',
    addUser: 'add-user',
    announcementList: 'announcement-list',
    classAttendance: 'class-attendance',
    classClass: 'class-class',
    classSetup: 'class-setup',
    // 'create-announcement', 
    // 'create-class-setup', 
    // 'create-session-class', 
    // 'create-staff', 
    // 'create-student', 
    // 'create-subject-setup', 
    // 'cummulative-master-list', 
    // 'delete-announcement', 
    // 'delete-class-register', 
    // 'delete-class-setup', 
    deleteSession: 'delete-session',
    // 'delete-session-class', 
    // 'delete-staff', 
    // 'delete-student', 
    // 'delete-subject-setup', 
    // 'edit-announcement', 
    // 'edit-class-setup', 
    // 'edit-role', 
    // 'edit-session-class', 
    // 'edit-staff', 
    // 'edit-student', 
    // 'edit-subject-setup', 
    // 'enrolled-students-list', 
    // 'enroll-students', 
    // 'export-cummulative-master', 
    // 'export-master-list', 
    // 'grade-setting', 
    // 'master-list', 
    // 'new-role', 
    // 'portal-setting', 
    // 'previous-terms-scores', 
    // 'print-result', 
    // 'promote-students', 
    // 'promotion-list', 
    // 'publish-result', 
    // 'role-list', 
    // 'score-entry', 
    // 'session-class', 
    sessionSetup: 'session-setup',
    // 'student-list', 
    subjectSetup: 'subject-setup',
    // 'switch-terms', 
    // 'template-setting', 
    // 'total-classes', 
    // 'total-enrolled-student', 
    // 'total-pins', 
    // 'total-staff', 
    // 'total-subjects', 
    // 'unenroll students', 
    // 'unenrolled-students-list', 
    // 'unused-pins', 
    // 'upload-pins', 
    // 'used-pins', 
    // 'view-results-to-publish'
}



export const hasAccess = (nav) => {
    const permissions = localStorage.getItem('permissions').split(',');
    return permissions.find(d => d == nav) ? true : false;
}