export const actions = {
    PUSH_UNENROLLED_STUDENT_ID: "PUSH_UNENROLLED_STUDENT_ID",
    REMOVE_UNENROLLED_STUDENT_ID: "REMOVE_UNENROLLED_STUDENT_ID",
    RETURN_UNENROLLED_STUDENT_LIST: "RETURN_UNENROLLED_STUDENT_LIST",
  
    FETCH_UNENROLLED_STUDENTS_LOADING: "FETCH_UNENROLLED_STUDENTS_LOADING",
    FETCH_UNENROLLED_STUDENTS_SUCCESS: "FETCH_UNENROLLED_STUDENTS_SUCCESS",
    FETCH_UNENROLLED_STUDENTS_FAILED: "FETCH_UNENROLLED_STUDENTS_FAILED",

    ENROLL_STUDENT_LOADING: "ENROLL_STUDENT_LOADING",
    ENROLL_STUDENT_SUCCESS: "ENROLL_STUDENT_SUCCESS",
    ENROLL_STUDENT_FAILED: "ENROLL_STUDENT_FAILED",

    FETCH_ENROLLED_STUDENTS_LOADING: "FETCH_ENROLLED_STUDENTS_LOADING",
    FETCH_ENROLLED_STUDENTS_SUCCESS: "FETCH_ENROLLED_STUDENTS_SUCCESS",
    FETCH_ENROLLED_STUDENTS_FAILED: "FETCH_ENROLLED_STUDENTS_FAILED",

    UNENROLL_STUDENTS_LOADING: "UNENROLL_STUDENTS_LOADING",
    UNENROLL_STUDENTS_SUCCESS: "UNENROLL_STUDENTS_SUCCESS",
    UNENROLL_STUDENTS_FAILED: "UNENROLL_STUDENTS_FAILED",
}