export const actions = {
    RESET_SCREEN: 'RESET_SCREEN',
    
    FETCH_ACTIVE_SESSION_LOADING: 'FETCH_ACTIVE_SESSION_LOADING',
    FETCH_ACTIVE_SESSION_SUCCESS: 'FETCH_ACTIVE_SESSION_SUCCESS',
    FETCH_ACTIVE_SESSION_FAILED: 'FETCH_ACTIVE_SESSION_FAILED'
}